# Generated by configure; do not edit

all:
	/usr/bin/ninja -C /home/alatiera/projects/rust/hammond/_build

install:
	DESTDIR="$(DESTDIR)" /usr/bin/ninja -C /home/alatiera/projects/rust/hammond/_build install

uninstall:
	/usr/bin/ninja -C /home/alatiera/projects/rust/hammond/_build uninstall

release:
	/usr/bin/ninja -C /home/alatiera/projects/rust/hammond/_build release

check:
	/usr/bin/mesontest -C /home/alatiera/projects/rust/hammond/_build
